### ISSUE TITLE
Credentails seem not to work

### ISSUE THREAD

**Issue by Franz-Ritter** [RHEAGROUP/COMET-Docker-Compose#14]
Hi, 
I just executed the docker compose script `./docker.sh test` to start an instance with test data. once the image is pulled I tried to access the page on http://localhost:5000/SiteDirectory.
It seems that the described credentails admin/pass  seems not to work since I receive a status 401 - unauthorized. Can you please confirm that the described credentails work.

**Comment by alexatrhea** [comment]
The "test" command spools up a completely bare database which contains no users and is not used for anything other than running the webservices integration tests (the integration test procedure populates the database on its own). If you want to use a populated database you should use "up" command.

I do agree that this should be made clearer in the Readme.
